remote_theme: pmarsceill/just-the-docs
title: SHREAD
description: Snow-Hydrology Repo for Evaluation, Analysis, and Decision-making
logo: "https://github.com/usbr/SHREAD/blob/master/resources/images/logo_shread.png"
